name: carinsight-pro
services:
  - name: frontend
    source_dir: /frontend
    github:
      repo: AdanD9/car-price-predictor
      branch: master
    run_command: npm start
    build_command: npm run build
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /

  - name: backend
    source_dir: /backend
    github:
      repo: AdanD9/car-price-predictor
      branch: master
    run_command: uvicorn main:app --host 0.0.0.0 --port 8080
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xs
    http_port: 8080
    routes:
      - path: /api
